on:
  push:
    branches:
      - dev

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: BuildAndPublish
  steps:
  - script: 
  - task: PublishBuildArtifacts@1
    displayName: 'Publish notification as artifact'
    inputs:
      PathtoPublish: '$(System.DefaultWorkingDirectory)/notification.txt'
      ArtifactName: 'PushNotification'
      publishLocation: 'Container'
