on:
  push:
    branches:
      - dev

jobs:
  BuildAndPublish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Publish notification as artifact
        uses: actions/upload-artifact@v3
        with:
          name: PushNotification
          path: notification.txt
