on:
  push:
    branches:
      - dev

jobs:
  BuildAndPublish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.4.2
      - name: Create notification file
        run: echo "Build and publish job completed successfully" > notification.txt
      - name: Publish notification as artifact
        uses: actions/upload-artifact@v4.4.2
        with:
          name: PushNotification
          path: notification.txt
